### ISSUE TITLE
error message：Too short switch

### ISSUE THREAD

**Issue by Leonyan938** [Wilnk/Google-Drive-Online-Decompression#11]
Hello,

I tried few zip, rar, and 7zip compressed file, but I always get below error message. 

May I ask how to fix this?

Thanks!

Command Line Error:
Too short switch:
-o

**Comment by Wilnk** [comment]
Did you modify any internal code?

Error means that the internal code interface -o has an error and has been modified.

When I tested it, there was no task problem. You may try to git again.

**Comment by Leonyan938** [comment]
Thanks Wilink!

This error was caused because I didn't type in file unzip destination location. I thought if I leave it blank then script would unzip file into the current folder. 

All good now
