### ISSUE TITLE
绑定云盘出错

### ISSUE THREAD

**Issue by yysm** [Wilnk/Google-Drive-Online-Decompression#2]
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py in _input_request(self, prompt, ident, parent, password)
    728             try:
--> 729                 ident, reply = self.session.recv(self.stdin_socket, 0)
    730             except Exception:

6 frames
/usr/local/lib/python3.6/dist-packages/jupyter_client/session.py in recv(self, socket, mode, content, copy)
    802         try:
--> 803             msg_list = socket.recv_multipart(mode, copy=copy)
    804         except zmq.ZMQError as e:

/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py in recv_multipart(self, flags, copy, track)
    474         """
--> 475         parts = [self.recv(flags, copy=copy, track=track)]
    476         # have first part already, only loop while more to receive

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()

/usr/local/lib/python3.6/dist-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()

KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

/usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    240       auth_prompt = d.match.group(1) + '\nEnter your authorization code:\n'
    241       with open(fifo, 'w') as fifo_file:
--> 242         fifo_file.write(_getpass.getpass(auth_prompt) + '\n')
    243       wrote_to_fifo = True
    244   if not wrote_to_fifo:

/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py in getpass(self, prompt, stream)
    685             self._parent_ident,
    686             self._parent_header,
--> 687             password=True,
    688         )
    689 

/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py in _input_request(self, prompt, ident, parent, password)
    732             except KeyboardInterrupt:
    733                 # re-raise KeyboardInterrupt, to truncate traceback
--> 734                 raise KeyboardInterrupt
    735             else:
    736                 break

KeyboardInterrupt:

**Comment by Wilnk** [comment]
请重新测试，或者换个账号，内容是经过测试的。

检测授权码是否复制正确。谢谢

**Comment by yysm** [comment]
换了帐号一样的问题，授权码没问题试了好几次了

**Comment by Wilnk** [comment]
但是我这边测试没问题啊

![image](https://user-images.githubusercontent.com/46810638/87755606-e04c2880-c839-11ea-9396-88f06ceb99eb.png)

你的教育账号还是个人账号？

**Comment by yysm** [comment]
个人和教育帐号都一样，我都试过了

**Comment by Wilnk** [comment]
试试浏览器的无痕模式
