### ISSUE TITLE
請問出現以下錯誤該如何解決?THX

### ISSUE THREAD

**Issue by clode1002** [Wilnk/Google-Drive-Online-Decompression#3]
Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
Unexpected token < in JSON at position 5

**Comment by Wilnk** [comment]
重新连接，应该节点不行，断流了。

**Comment by BillyJr0127** [comment]
我也有一樣的問題.. 但其他的都可以正常使用 :\
