### ISSUE TITLE
terminate called after throwing an instance of 'CInBufferException'

### ISSUE THREAD

**Issue by efklf3k3i3** [Wilnk/Google-Drive-Online-Decompression#4]
教育帳號

解壓到一半出現錯誤就不動了

 47% 220 - Lesson 063-64 Thank you, doctor/Lesson63&64知识拓展.mp4terminate called after throwing an instance of 'CInBufferException'

**Comment by Wilnk** [comment]
程序还有没有在跑？还是直接中断了还是红叉警告？右上角是否还在连接中？

**Comment by luceng** [comment]
我也出现这种错误，右上角已连接，跑到一半暂停了一会，然后就自动中断，接着就出现这话，没有红叉警告

**Comment by Wilnk** [comment]
解压的文件多大的？用什么格式解压？

**Comment by luceng** [comment]
批量解压zip，带有密码，密码一样，文件夹总共573g，正在解压的包是40g

**Comment by Wilnk** [comment]
超出额度了，被Colab检测到然后强行杀死了。

如果你没有改的运行模式的话默认分配是68G，如果你改了的话是107G。

而且这个占用的额度是单个用户的每日配额750G，建议解压100G以内的资源。

**Comment by Wilnk** [comment]
查看当前用户运行分配多少额度可以直接鼠标移到右上角已连接的按钮上会弹出消息框。

**Comment by luceng** [comment]
但我那个40g的包都还没解压到一半，应该不会超啊

**Comment by luceng** [comment]
45.42/107.77

**Comment by Wilnk** [comment]
分压包卷嘛？你用的哪个批量解压？

**Comment by luceng** [comment]
不是分压包卷，就只是各个压缩包独立的，用的是批量解压zip

**Comment by Wilnk** [comment]
总大小是否超过50G？因为是批量，所以会读取目录下所有的压缩包，并且同时解压。如果读取和解压压缩包总大小在缓存中超过100的话Colab便会终止程序。

建议总容量的大的话 分批次解压
