### ISSUE TITLE
请问这样该怎么办？如图所示

### ISSUE THREAD

**Issue by ephao** [Wilnk/Google-Drive-Online-Decompression#5]
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.30GHz (306F0),ASM,AES-NI)

Scanning the drive for archives:

ERROR: No more files
 

System ERROR:
Unknown error -2147024872
如图所示
<img width="899" alt="chrome_2020-07-17_16-37-31" src="https://user-images.githubusercontent.com/26166901/87766679-201c0b80-c84c-11ea-8df6-55b86abb03e1.png">

**Comment by Wilnk** [comment]
先看看能不能读取目录，如果读取没问题，看看解压包有没有密码？如果没有问题，那应该有可能是解压包损坏了，这种情况建议下载本地解压。

如果是刚转存的文件，建议等一段时间再解压。等Google Drive服务器加载完全。

**Comment by ephao** [comment]
我又试了一下从本地上传的文件242.rar，还是找不到
<img width="662" alt="chrome_2020-07-17_16-51-36" src="https://user-images.githubusercontent.com/26166901/87767926-f5cb4d80-c84d-11ea-9145-fb9106ebce4b.png">

**Comment by ephao** [comment]
242.rar也就几百k的大小

**Comment by Wilnk** [comment]
一般是可以正常查看的，你用通用查看的试试。你用格式什么压缩的？是WINZIP还是WINRAR的格式？

**Comment by ephao** [comment]
通用查看的结果和第一张图的错误代码一样，是winrar格式的

**Comment by ephao** [comment]
<img width="909" alt="chrome_2020-07-17_17-02-43" src="https://user-images.githubusercontent.com/26166901/87769027-92dab600-c84f-11ea-9cca-92756733ebb6.png">
同样的文件我又用zip格式压缩了一下，上传之后还是无法解压

**Comment by Wilnk** [comment]
文件可否传送过过来？我这边测试是正常的

**Comment by ephao** [comment]
https://drive.google.com/file/d/1M5WVWM3bvCPdJ1ZhN9ORViJfqBWdziZ3/view?usp=sharing

**Comment by ephao** [comment]
https://drive.google.com/file/d/17AYyXO-zcVbjFgyn-YNoxEVFalL1Lv_6/view?usp=sharing
这个是我想要解压的文件，麻烦您帮忙看看这个

**Comment by Wilnk** [comment]
我这边测试是通过的哟

![image](https://user-images.githubusercontent.com/46810638/87770428-9a02c380-c851-11ea-8446-63c5de7ce7b5.png)


![image](https://user-images.githubusercontent.com/46810638/87770397-92dbb580-c851-11ea-99c8-e66a86b491a4.png)

**Comment by ephao** [comment]
这样应该是安装成功了吧
<img width="921" alt="chrome_2020-07-17_17-22-16" src="https://user-images.githubusercontent.com/26166901/87770922-362cca80-c852-11ea-989d-f6878e7e1ccc.png">

**Comment by Wilnk** [comment]
对啊这样是成功的

![image](https://user-images.githubusercontent.com/46810638/87771039-62e0e200-c852-11ea-9399-66d6aaa4c794.png)

**Comment by ephao** [comment]
虽然不知道为什么，但突然可以了:joy::joy::joy:
谢谢你啦

**Comment by Wilnk** [comment]
客气，如果没什么问题我就关闭这个对话咯？

**Comment by ephao** [comment]
没有啦，关闭吧:smile::smile::smile:
