### ISSUE TITLE
用一段時間會當掉

### ISSUE THREAD

**Issue by AlbertChangSLW** [Wilnk/Google-Drive-Online-Decompression#8]
好像用一段時間會跟掛載的GD斷線
好像用一段時間就會當掉
重新整理沒用
我上網查過好像是說90分鐘會斷線一次
在另一個大大好像說要加一段代碼在console底下
請問大大知道怎麼加嗎
或者大大的腳本有辦法修改?

**Comment by karickkl** [comment]
可參考gd-utils colab 版的腳本

**Comment by Wilnk** [comment]
每60分钟自动运行代码以刷新90分钟断开限制. 打开 developer-settings (在你的浏览器) 快速健 Ctrl+Shift+I 然后按console 输入以下代码 Enter. ( mac 按 Option+Command+I)

复制以下隐藏代码粉贴在浏览器console！！不要关闭浏览器以免失效

function ClickConnect(){ console.log("Working"); document.querySelector("colab-connect-button").click() }setInterval(ClickConnect,6000)

或者你插入这个代码片段也行

#@markdown <h3>← 输入了代码后运行以防止断开</h>


import IPython
from google.colab import output

display(IPython.display.Javascript('''
 function ClickConnect(){
   btn = document.querySelector("colab-connect-button")
   if (btn != null){
     console.log("Click colab-connect-button"); 
     btn.click() 
     }
   
   btn = document.getElementById('ok')
   if (btn != null){
     console.log("Click reconnect"); 
     btn.click() 
     }
  }
  
setInterval(ClickConnect,60000)
'''))

print("Done.")

**Comment by Wilnk** [comment]
更新了代码，添加了脚本。从新拉取即可。
